name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'TF action'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Vars
        run: |
          cat <<EOF >>terraform.tfvars
          vpc_id                       = "vpc-86785de1"
          public_subnet_id             = "subnet-9a5e53fd"
          route_table_ids              = ["rtb-0ae427e9c1c1fdddb", "rtb-08820989a3e4b8b56", "rtb-0c42dc2eb01c64062"]
          security_group_inbound_cidrs = ["172.32.0.0/16", "172.33.0.0/16"]
          tags                         = { Shutdown = "Night" }
          EOF

      - name: Terraform Init
        run: |
          cat <<EOF >>backend.tf
          terraform {
            backend "s3" {}
          }
          EOF
          terraform init \
            -backend-config="bucket=terragrunt-terraform" \
            -backend-config="key=lab/aws-vpc-nat-instance/terraform.tfstate" \
            -backend-config="region=ap-southeast-2"

      - name: Terraform Plan
        if: ${{ inputs.action == 'apply' }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        run: terraform apply -auto-approve -input=false tfplan

      - name: Terraform Destroy
        if: ${{ inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -input=false
